//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Ale\Desktop\Compiler Sheila\Compiler\Logic\Parser\Grammar\coolgrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class coolgrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, STR=20, CLASS=21, INHERITS=22, LET=23, IN=24, WS=25, 
		IF=26, THEN=27, ELSE=28, FI=29, WHILE=30, LOOP=31, POOL=32, NEW=33, TYPE=34, 
		ISVOID=35, INTEGER=36, TRUE=37, FALSE=38, NOT=39, CASE=40, OF=41, ESAC=42, 
		ID=43;
	public const int
		RULE_program = 0, RULE_class = 1, RULE_feature = 2, RULE_method = 3, RULE_attr = 4, 
		RULE_formal = 5, RULE_expr = 6, RULE_branch = 7, RULE_expr_list = 8, RULE_args_def = 9, 
		RULE_args_call = 10;
	public static readonly string[] ruleNames = {
		"program", "class", "feature", "method", "attr", "formal", "expr", "branch", 
		"expr_list", "args_def", "args_call"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'{'", "'}'", "'('", "')'", "':'", "'<-'", "'@'", "'.'", 
		"'~'", "'*'", "'/'", "'+'", "'-'", "'<'", "'<='", "'='", "','", "'=>'", 
		null, "'class'", "'inherits'", "'let'", "'in'", null, "'if'", "'then'", 
		"'else'", "'fi'", "'while'", "'loop'", "'pool'", "'new'", null, "'isvoid'", 
		null, "'true'", "'false'", "'not'", "'case'", "'of'", "'esac'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "STR", "CLASS", "INHERITS", 
		"LET", "IN", "WS", "IF", "THEN", "ELSE", "FI", "WHILE", "LOOP", "POOL", 
		"NEW", "TYPE", "ISVOID", "INTEGER", "TRUE", "FALSE", "NOT", "CASE", "OF", 
		"ESAC", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "coolgrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static coolgrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public coolgrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public coolgrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class ProgramContext : ParserRuleContext {
		public ClassContext[] @class() {
			return GetRuleContexts<ClassContext>();
		}
		public ClassContext @class(int i) {
			return GetRuleContext<ClassContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 25;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 22; @class();
				State = 23; Match(T__0);
				}
				}
				State = 27;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==CLASS );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassContext : ParserRuleContext {
		public ITerminalNode CLASS() { return GetToken(coolgrammarParser.CLASS, 0); }
		public ITerminalNode[] TYPE() { return GetTokens(coolgrammarParser.TYPE); }
		public ITerminalNode TYPE(int i) {
			return GetToken(coolgrammarParser.TYPE, i);
		}
		public ITerminalNode INHERITS() { return GetToken(coolgrammarParser.INHERITS, 0); }
		public FeatureContext[] feature() {
			return GetRuleContexts<FeatureContext>();
		}
		public FeatureContext feature(int i) {
			return GetRuleContext<FeatureContext>(i);
		}
		public ClassContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClass(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassContext @class() {
		ClassContext _localctx = new ClassContext(Context, State);
		EnterRule(_localctx, 2, RULE_class);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 29; Match(CLASS);
			State = 30; Match(TYPE);
			State = 33;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==INHERITS) {
				{
				State = 31; Match(INHERITS);
				State = 32; Match(TYPE);
				}
			}

			State = 35; Match(T__1);
			State = 41;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ID) {
				{
				{
				State = 36; feature();
				State = 37; Match(T__0);
				}
				}
				State = 43;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 44; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FeatureContext : ParserRuleContext {
		public FeatureContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_feature; } }
	 
		public FeatureContext() { }
		public virtual void CopyFrom(FeatureContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class F_methodContext : FeatureContext {
		public MethodContext method() {
			return GetRuleContext<MethodContext>(0);
		}
		public F_methodContext(FeatureContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitF_method(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class F_attrContext : FeatureContext {
		public AttrContext attr() {
			return GetRuleContext<AttrContext>(0);
		}
		public F_attrContext(FeatureContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitF_attr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FeatureContext feature() {
		FeatureContext _localctx = new FeatureContext(Context, State);
		EnterRule(_localctx, 4, RULE_feature);
		try {
			State = 48;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				_localctx = new F_attrContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 46; attr();
				}
				break;
			case 2:
				_localctx = new F_methodContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 47; method();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(coolgrammarParser.ID, 0); }
		public Args_defContext args_def() {
			return GetRuleContext<Args_defContext>(0);
		}
		public ITerminalNode TYPE() { return GetToken(coolgrammarParser.TYPE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public MethodContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethod(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodContext method() {
		MethodContext _localctx = new MethodContext(Context, State);
		EnterRule(_localctx, 6, RULE_method);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50; Match(ID);
			State = 51; Match(T__3);
			State = 52; args_def();
			State = 53; Match(T__4);
			State = 54; Match(T__5);
			State = 55; Match(TYPE);
			State = 56; Match(T__1);
			State = 57; expr(0);
			State = 58; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttrContext : ParserRuleContext {
		public FormalContext formal() {
			return GetRuleContext<FormalContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AttrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attr; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttrContext attr() {
		AttrContext _localctx = new AttrContext(Context, State);
		EnterRule(_localctx, 8, RULE_attr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60; formal();
			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 61; Match(T__6);
				State = 62; expr(0);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormalContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(coolgrammarParser.ID, 0); }
		public ITerminalNode TYPE() { return GetToken(coolgrammarParser.TYPE, 0); }
		public FormalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formal; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormal(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormalContext formal() {
		FormalContext _localctx = new FormalContext(Context, State);
		EnterRule(_localctx, 10, RULE_formal);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65; Match(ID);
			State = 66; Match(T__5);
			State = 67; Match(TYPE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class BodyContext : ExprContext {
		public Expr_listContext expr_list() {
			return GetRuleContext<Expr_listContext>(0);
		}
		public BodyContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBody(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CompContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public CompContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AssignContext : ExprContext {
		public ITerminalNode ID() { return GetToken(coolgrammarParser.ID, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssignContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssign(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LetContext : ExprContext {
		public ITerminalNode LET() { return GetToken(coolgrammarParser.LET, 0); }
		public AttrContext[] attr() {
			return GetRuleContexts<AttrContext>();
		}
		public AttrContext attr(int i) {
			return GetRuleContext<AttrContext>(i);
		}
		public ITerminalNode IN() { return GetToken(coolgrammarParser.IN, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public LetContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLet(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Neg_bitContext : ExprContext {
		public IToken op;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Neg_bitContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNeg_bit(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntContext : ExprContext {
		public ITerminalNode INTEGER() { return GetToken(coolgrammarParser.INTEGER, 0); }
		public IntContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IsvoidContext : ExprContext {
		public ITerminalNode ISVOID() { return GetToken(coolgrammarParser.ISVOID, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public IsvoidContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIsvoid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Case_ofContext : ExprContext {
		public ITerminalNode CASE() { return GetToken(coolgrammarParser.CASE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode OF() { return GetToken(coolgrammarParser.OF, 0); }
		public ITerminalNode ESAC() { return GetToken(coolgrammarParser.ESAC, 0); }
		public BranchContext[] branch() {
			return GetRuleContexts<BranchContext>();
		}
		public BranchContext branch(int i) {
			return GetRuleContext<BranchContext>(i);
		}
		public Case_ofContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCase_of(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SumarestaContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public SumarestaContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSumaresta(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class If_elseContext : ExprContext {
		public ITerminalNode IF() { return GetToken(coolgrammarParser.IF, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode THEN() { return GetToken(coolgrammarParser.THEN, 0); }
		public ITerminalNode ELSE() { return GetToken(coolgrammarParser.ELSE, 0); }
		public ITerminalNode FI() { return GetToken(coolgrammarParser.FI, 0); }
		public If_elseContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf_else(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class WhileContext : ExprContext {
		public ITerminalNode WHILE() { return GetToken(coolgrammarParser.WHILE, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode LOOP() { return GetToken(coolgrammarParser.LOOP, 0); }
		public ITerminalNode POOL() { return GetToken(coolgrammarParser.POOL, 0); }
		public WhileContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdContext : ExprContext {
		public ITerminalNode ID() { return GetToken(coolgrammarParser.ID, 0); }
		public IdContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitId(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Call_methodContext : ExprContext {
		public ITerminalNode ID() { return GetToken(coolgrammarParser.ID, 0); }
		public Args_callContext args_call() {
			return GetRuleContext<Args_callContext>(0);
		}
		public Call_methodContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall_method(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class New_typeContext : ExprContext {
		public ITerminalNode NEW() { return GetToken(coolgrammarParser.NEW, 0); }
		public ITerminalNode TYPE() { return GetToken(coolgrammarParser.TYPE, 0); }
		public New_typeContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNew_type(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MultdivContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public MultdivContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultdiv(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParentesisContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ParentesisContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParentesis(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Not_expContext : ExprContext {
		public ITerminalNode NOT() { return GetToken(coolgrammarParser.NOT, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Not_expContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNot_exp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringContext : ExprContext {
		public ITerminalNode STR() { return GetToken(coolgrammarParser.STR, 0); }
		public StringContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class If_thenContext : ExprContext {
		public ITerminalNode IF() { return GetToken(coolgrammarParser.IF, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode THEN() { return GetToken(coolgrammarParser.THEN, 0); }
		public ITerminalNode FI() { return GetToken(coolgrammarParser.FI, 0); }
		public If_thenContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf_then(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DispatchContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode ID() { return GetToken(coolgrammarParser.ID, 0); }
		public Args_callContext args_call() {
			return GetRuleContext<Args_callContext>(0);
		}
		public ITerminalNode TYPE() { return GetToken(coolgrammarParser.TYPE, 0); }
		public DispatchContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDispatch(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolContext : ExprContext {
		public IToken cons;
		public ITerminalNode TRUE() { return GetToken(coolgrammarParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(coolgrammarParser.FALSE, 0); }
		public BoolContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBool(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 12;
		EnterRecursionRule(_localctx, 12, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 142;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				{
				_localctx = new Call_methodContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 70; Match(ID);
				State = 71; Match(T__3);
				State = 72; args_call();
				State = 73; Match(T__4);
				}
				break;
			case 2:
				{
				_localctx = new If_thenContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 75; Match(IF);
				State = 76; expr(0);
				State = 77; Match(THEN);
				State = 78; expr(0);
				State = 79; Match(FI);
				}
				break;
			case 3:
				{
				_localctx = new If_elseContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 81; Match(IF);
				State = 82; expr(0);
				State = 83; Match(THEN);
				State = 84; expr(0);
				State = 85; Match(ELSE);
				State = 86; expr(0);
				State = 87; Match(FI);
				}
				break;
			case 4:
				{
				_localctx = new WhileContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 89; Match(WHILE);
				State = 90; expr(0);
				State = 91; Match(LOOP);
				State = 92; expr(0);
				State = 93; Match(POOL);
				}
				break;
			case 5:
				{
				_localctx = new BodyContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 95; Match(T__1);
				State = 96; expr_list();
				State = 97; Match(T__2);
				}
				break;
			case 6:
				{
				_localctx = new Case_ofContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 99; Match(CASE);
				State = 100; expr(0);
				State = 101; Match(OF);
				State = 105;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 102; branch();
					State = 103; Match(T__0);
					}
					}
					State = 107;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==ID );
				State = 109; Match(ESAC);
				}
				break;
			case 7:
				{
				_localctx = new New_typeContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 111; Match(NEW);
				State = 112; Match(TYPE);
				}
				break;
			case 8:
				{
				_localctx = new Neg_bitContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 113; ((Neg_bitContext)_localctx).op = Match(T__9);
				State = 114; expr(13);
				}
				break;
			case 9:
				{
				_localctx = new IsvoidContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 115; Match(ISVOID);
				State = 116; expr(12);
				}
				break;
			case 10:
				{
				_localctx = new Not_expContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 117; Match(NOT);
				State = 118; expr(8);
				}
				break;
			case 11:
				{
				_localctx = new ParentesisContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 119; Match(T__3);
				State = 120; expr(0);
				State = 121; Match(T__4);
				}
				break;
			case 12:
				{
				_localctx = new IntContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 123; Match(INTEGER);
				}
				break;
			case 13:
				{
				_localctx = new BoolContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 124;
				((BoolContext)_localctx).cons = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==TRUE || _la==FALSE) ) {
					((BoolContext)_localctx).cons = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 14:
				{
				_localctx = new StringContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 125; Match(STR);
				}
				break;
			case 15:
				{
				_localctx = new AssignContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 126; Match(ID);
				State = 127; Match(T__6);
				State = 128; expr(3);
				}
				break;
			case 16:
				{
				_localctx = new LetContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 129; Match(LET);
				State = 130; attr();
				State = 135;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__17) {
					{
					{
					State = 131; Match(T__17);
					State = 132; attr();
					}
					}
					State = 137;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 138; Match(IN);
				State = 139; expr(2);
				}
				break;
			case 17:
				{
				_localctx = new IdContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 141; Match(ID);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 166;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 164;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
					case 1:
						{
						_localctx = new MultdivContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 144;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 145;
						((MultdivContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==T__10 || _la==T__11) ) {
							((MultdivContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 146; expr(12);
						}
						break;
					case 2:
						{
						_localctx = new SumarestaContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 147;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 148;
						((SumarestaContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==T__12 || _la==T__13) ) {
							((SumarestaContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 149; expr(11);
						}
						break;
					case 3:
						{
						_localctx = new CompContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 150;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 151;
						((CompContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__14) | (1L << T__15) | (1L << T__16))) != 0)) ) {
							((CompContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 152; expr(10);
						}
						break;
					case 4:
						{
						_localctx = new DispatchContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 153;
						if (!(Precpred(Context, 21))) throw new FailedPredicateException(this, "Precpred(Context, 21)");
						State = 156;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if (_la==T__7) {
							{
							State = 154; Match(T__7);
							State = 155; Match(TYPE);
							}
						}

						State = 158; Match(T__8);
						State = 159; Match(ID);
						State = 160; Match(T__3);
						State = 161; args_call();
						State = 162; Match(T__4);
						}
						break;
					}
					} 
				}
				State = 168;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class BranchContext : ParserRuleContext {
		public FormalContext formal() {
			return GetRuleContext<FormalContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public BranchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_branch; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBranch(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BranchContext branch() {
		BranchContext _localctx = new BranchContext(Context, State);
		EnterRule(_localctx, 14, RULE_branch);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169; formal();
			State = 170; Match(T__18);
			State = 171; expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expr_listContext : ParserRuleContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Expr_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr_list; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expr_listContext expr_list() {
		Expr_listContext _localctx = new Expr_listContext(Context, State);
		EnterRule(_localctx, 16, RULE_expr_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 173; expr(0);
				State = 174; Match(T__0);
				}
				}
				State = 178;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__3) | (1L << T__9) | (1L << STR) | (1L << LET) | (1L << IF) | (1L << WHILE) | (1L << NEW) | (1L << ISVOID) | (1L << INTEGER) | (1L << TRUE) | (1L << FALSE) | (1L << NOT) | (1L << CASE) | (1L << ID))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Args_defContext : ParserRuleContext {
		public FormalContext[] formal() {
			return GetRuleContexts<FormalContext>();
		}
		public FormalContext formal(int i) {
			return GetRuleContext<FormalContext>(i);
		}
		public Args_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_args_def; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgs_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Args_defContext args_def() {
		Args_defContext _localctx = new Args_defContext(Context, State);
		EnterRule(_localctx, 18, RULE_args_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 180; formal();
				State = 185;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__17) {
					{
					{
					State = 181; Match(T__17);
					State = 182; formal();
					}
					}
					State = 187;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Args_callContext : ParserRuleContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Args_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_args_call; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IcoolgrammarVisitor<TResult> typedVisitor = visitor as IcoolgrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgs_call(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Args_callContext args_call() {
		Args_callContext _localctx = new Args_callContext(Context, State);
		EnterRule(_localctx, 20, RULE_args_call);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 198;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__3) | (1L << T__9) | (1L << STR) | (1L << LET) | (1L << IF) | (1L << WHILE) | (1L << NEW) | (1L << ISVOID) | (1L << INTEGER) | (1L << TRUE) | (1L << FALSE) | (1L << NOT) | (1L << CASE) | (1L << ID))) != 0)) {
				{
				State = 190; expr(0);
				State = 195;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__17) {
					{
					{
					State = 191; Match(T__17);
					State = 192; expr(0);
					}
					}
					State = 197;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 6: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 11);
		case 1: return Precpred(Context, 10);
		case 2: return Precpred(Context, 9);
		case 3: return Precpred(Context, 21);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '-', '\xCB', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x6', 
		'\x2', '\x1C', '\n', '\x2', '\r', '\x2', '\xE', '\x2', '\x1D', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '$', '\n', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 
		'*', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '-', '\v', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '\x33', 
		'\n', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x42', 
		'\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x6', '\b', 'l', '\n', '\b', '\r', '\b', 
		'\xE', '\b', 'm', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', '\b', '\x88', '\n', 
		'\b', '\f', '\b', '\xE', '\b', '\x8B', '\v', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x91', '\n', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x5', '\b', '\x9F', '\n', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', '\b', '\xA7', '\n', 
		'\b', '\f', '\b', '\xE', '\b', '\xAA', '\v', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x6', '\n', '\xB3', '\n', '\n', '\r', '\n', '\xE', '\n', '\xB4', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\a', '\v', '\xBA', '\n', '\v', '\f', 
		'\v', '\xE', '\v', '\xBD', '\v', '\v', '\x5', '\v', '\xBF', '\n', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\xC4', '\n', '\f', 
		'\f', '\f', '\xE', '\f', '\xC7', '\v', '\f', '\x5', '\f', '\xC9', '\n', 
		'\f', '\x3', '\f', '\x2', '\x3', '\xE', '\r', '\x2', '\x4', '\x6', '\b', 
		'\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x2', '\x6', '\x3', 
		'\x2', '\'', '(', '\x3', '\x2', '\r', '\xE', '\x3', '\x2', '\xF', '\x10', 
		'\x3', '\x2', '\x11', '\x13', '\x2', '\xE0', '\x2', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\x4', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x6', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\b', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\n', '>', '\x3', '\x2', '\x2', '\x2', '\f', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\xE', '\x90', '\x3', '\x2', '\x2', '\x2', '\x10', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\x12', '\xB2', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\x16', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\x18', '\x19', '\x5', '\x4', '\x3', '\x2', '\x19', '\x1A', '\a', 
		'\x3', '\x2', '\x2', '\x1A', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x18', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', '\x3', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		' ', '\a', '\x17', '\x2', '\x2', ' ', '#', '\a', '$', '\x2', '\x2', '!', 
		'\"', '\a', '\x18', '\x2', '\x2', '\"', '$', '\a', '$', '\x2', '\x2', 
		'#', '!', '\x3', '\x2', '\x2', '\x2', '#', '$', '\x3', '\x2', '\x2', '\x2', 
		'$', '%', '\x3', '\x2', '\x2', '\x2', '%', '+', '\a', '\x4', '\x2', '\x2', 
		'&', '\'', '\x5', '\x6', '\x4', '\x2', '\'', '(', '\a', '\x3', '\x2', 
		'\x2', '(', '*', '\x3', '\x2', '\x2', '\x2', ')', '&', '\x3', '\x2', '\x2', 
		'\x2', '*', '-', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', 
		'\x2', '+', ',', '\x3', '\x2', '\x2', '\x2', ',', '.', '\x3', '\x2', '\x2', 
		'\x2', '-', '+', '\x3', '\x2', '\x2', '\x2', '.', '/', '\a', '\x5', '\x2', 
		'\x2', '/', '\x5', '\x3', '\x2', '\x2', '\x2', '\x30', '\x33', '\x5', 
		'\n', '\x6', '\x2', '\x31', '\x33', '\x5', '\b', '\x5', '\x2', '\x32', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x32', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\a', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\a', 
		'-', '\x2', '\x2', '\x35', '\x36', '\a', '\x6', '\x2', '\x2', '\x36', 
		'\x37', '\x5', '\x14', '\v', '\x2', '\x37', '\x38', '\a', '\a', '\x2', 
		'\x2', '\x38', '\x39', '\a', '\b', '\x2', '\x2', '\x39', ':', '\a', '$', 
		'\x2', '\x2', ':', ';', '\a', '\x4', '\x2', '\x2', ';', '<', '\x5', '\xE', 
		'\b', '\x2', '<', '=', '\a', '\x5', '\x2', '\x2', '=', '\t', '\x3', '\x2', 
		'\x2', '\x2', '>', '\x41', '\x5', '\f', '\a', '\x2', '?', '@', '\a', '\t', 
		'\x2', '\x2', '@', '\x42', '\x5', '\xE', '\b', '\x2', '\x41', '?', '\x3', 
		'\x2', '\x2', '\x2', '\x41', '\x42', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'\v', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', '-', '\x2', '\x2', 
		'\x44', '\x45', '\a', '\b', '\x2', '\x2', '\x45', '\x46', '\a', '$', '\x2', 
		'\x2', '\x46', '\r', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\b', '\b', 
		'\x1', '\x2', 'H', 'I', '\a', '-', '\x2', '\x2', 'I', 'J', '\a', '\x6', 
		'\x2', '\x2', 'J', 'K', '\x5', '\x16', '\f', '\x2', 'K', 'L', '\a', '\a', 
		'\x2', '\x2', 'L', '\x91', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', 
		'\x1C', '\x2', '\x2', 'N', 'O', '\x5', '\xE', '\b', '\x2', 'O', 'P', '\a', 
		'\x1D', '\x2', '\x2', 'P', 'Q', '\x5', '\xE', '\b', '\x2', 'Q', 'R', '\a', 
		'\x1F', '\x2', '\x2', 'R', '\x91', '\x3', '\x2', '\x2', '\x2', 'S', 'T', 
		'\a', '\x1C', '\x2', '\x2', 'T', 'U', '\x5', '\xE', '\b', '\x2', 'U', 
		'V', '\a', '\x1D', '\x2', '\x2', 'V', 'W', '\x5', '\xE', '\b', '\x2', 
		'W', 'X', '\a', '\x1E', '\x2', '\x2', 'X', 'Y', '\x5', '\xE', '\b', '\x2', 
		'Y', 'Z', '\a', '\x1F', '\x2', '\x2', 'Z', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\a', ' ', '\x2', '\x2', '\\', ']', '\x5', '\xE', '\b', 
		'\x2', ']', '^', '\a', '!', '\x2', '\x2', '^', '_', '\x5', '\xE', '\b', 
		'\x2', '_', '`', '\a', '\"', '\x2', '\x2', '`', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x61', '\x62', '\a', '\x4', '\x2', '\x2', '\x62', '\x63', 
		'\x5', '\x12', '\n', '\x2', '\x63', '\x64', '\a', '\x5', '\x2', '\x2', 
		'\x64', '\x91', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', '*', 
		'\x2', '\x2', '\x66', 'g', '\x5', '\xE', '\b', '\x2', 'g', 'k', '\a', 
		'+', '\x2', '\x2', 'h', 'i', '\x5', '\x10', '\t', '\x2', 'i', 'j', '\a', 
		'\x3', '\x2', '\x2', 'j', 'l', '\x3', '\x2', '\x2', '\x2', 'k', 'h', '\x3', 
		'\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', 'k', '\x3', 
		'\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'p', '\a', ',', '\x2', '\x2', 'p', '\x91', '\x3', 
		'\x2', '\x2', '\x2', 'q', 'r', '\a', '#', '\x2', '\x2', 'r', '\x91', '\a', 
		'$', '\x2', '\x2', 's', 't', '\a', '\f', '\x2', '\x2', 't', '\x91', '\x5', 
		'\xE', '\b', '\xF', 'u', 'v', '\a', '%', '\x2', '\x2', 'v', '\x91', '\x5', 
		'\xE', '\b', '\xE', 'w', 'x', '\a', ')', '\x2', '\x2', 'x', '\x91', '\x5', 
		'\xE', '\b', '\n', 'y', 'z', '\a', '\x6', '\x2', '\x2', 'z', '{', '\x5', 
		'\xE', '\b', '\x2', '{', '|', '\a', '\a', '\x2', '\x2', '|', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '}', '\x91', '\a', '&', '\x2', '\x2', '~', '\x91', 
		'\t', '\x2', '\x2', '\x2', '\x7F', '\x91', '\a', '\x16', '\x2', '\x2', 
		'\x80', '\x81', '\a', '-', '\x2', '\x2', '\x81', '\x82', '\a', '\t', '\x2', 
		'\x2', '\x82', '\x91', '\x5', '\xE', '\b', '\x5', '\x83', '\x84', '\a', 
		'\x19', '\x2', '\x2', '\x84', '\x89', '\x5', '\n', '\x6', '\x2', '\x85', 
		'\x86', '\a', '\x14', '\x2', '\x2', '\x86', '\x88', '\x5', '\n', '\x6', 
		'\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x88', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\a', 
		'\x1A', '\x2', '\x2', '\x8D', '\x8E', '\x5', '\xE', '\b', '\x4', '\x8E', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x91', '\a', '-', '\x2', 
		'\x2', '\x90', 'G', '\x3', '\x2', '\x2', '\x2', '\x90', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x90', 'S', '\x3', '\x2', '\x2', '\x2', '\x90', '[', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x61', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\x90', 'q', '\x3', '\x2', '\x2', 
		'\x2', '\x90', 's', '\x3', '\x2', '\x2', '\x2', '\x90', 'u', '\x3', '\x2', 
		'\x2', '\x2', '\x90', 'w', '\x3', '\x2', '\x2', '\x2', '\x90', 'y', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '}', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x90', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x80', '\x3', '\x2', '\x2', '\x2', '\x90', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\f', '\r', '\x2', 
		'\x2', '\x93', '\x94', '\t', '\x3', '\x2', '\x2', '\x94', '\xA7', '\x5', 
		'\xE', '\b', '\xE', '\x95', '\x96', '\f', '\f', '\x2', '\x2', '\x96', 
		'\x97', '\t', '\x4', '\x2', '\x2', '\x97', '\xA7', '\x5', '\xE', '\b', 
		'\r', '\x98', '\x99', '\f', '\v', '\x2', '\x2', '\x99', '\x9A', '\t', 
		'\x5', '\x2', '\x2', '\x9A', '\xA7', '\x5', '\xE', '\b', '\f', '\x9B', 
		'\x9E', '\f', '\x17', '\x2', '\x2', '\x9C', '\x9D', '\a', '\n', '\x2', 
		'\x2', '\x9D', '\x9F', '\a', '$', '\x2', '\x2', '\x9E', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', '\v', '\x2', 
		'\x2', '\xA1', '\xA2', '\a', '-', '\x2', '\x2', '\xA2', '\xA3', '\a', 
		'\x6', '\x2', '\x2', '\xA3', '\xA4', '\x5', '\x16', '\f', '\x2', '\xA4', 
		'\xA5', '\a', '\a', '\x2', '\x2', '\xA5', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\x92', '\x3', '\x2', '\x2', '\x2', '\xA6', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\x98', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', '\xF', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\x5', '\f', '\a', 
		'\x2', '\xAC', '\xAD', '\a', '\x15', '\x2', '\x2', '\xAD', '\xAE', '\x5', 
		'\xE', '\b', '\x2', '\xAE', '\x11', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB0', '\x5', '\xE', '\b', '\x2', '\xB0', '\xB1', '\a', '\x3', '\x2', 
		'\x2', '\xB1', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\x3', '\x2', '\x2', 
		'\x2', '\xB5', '\x13', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xBB', '\x5', 
		'\f', '\a', '\x2', '\xB7', '\xB8', '\a', '\x14', '\x2', '\x2', '\xB8', 
		'\xBA', '\x5', '\f', '\a', '\x2', '\xB9', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xBF', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\x15', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xC5', '\x5', '\xE', '\b', '\x2', '\xC1', '\xC2', '\a', '\x14', '\x2', 
		'\x2', '\xC2', '\xC4', '\x5', '\xE', '\b', '\x2', '\xC3', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC4', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC5', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC8', 
		'\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x12', '\x1D', '#', '+', '\x32', '\x41', 'm', '\x89', '\x90', 
		'\x9E', '\xA6', '\xA8', '\xB4', '\xBB', '\xBE', '\xC5', '\xC8',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
